### PR TITLE
Add quadEM

### PR DESCRIPTION
**Pull request by mrakitin**
Based on the modification of the QuadEM class: https://github.com/NSLS-II/nslsii/pull/42.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
Are they running a quadem using AD v33? This should be defined in nslsii instead of here I think.

**Comment by mrakitin** [comment]
@awalter-bnl, yes. See xref https://github.com/NSLS-II/nslsii/pull/42.

**Comment by awalter-bnl** [comment]
thanks for the link @mrakitin I must have missed that at some point !-)

**Comment by mrakitin** [comment]
Welcome, @awalter-bnl and no worries. I'll follow @tacaswell's suggestion on subclassing later, and will update this PR accordingly.

**Comment by mrakitin** [comment]
Tested on the beamline (`xf28id2-ws6`), looks OK, except the error:
```
In [1]: RE(bp.count([qem1], num=10))
Transient Scan ID: 3     Time: 2018/10/19 15:54:37
Persistent Unique Scan ID: '925bb8e2-42d9-4cbd-b8b5-21d70769b450'
New stream: 'primary'
+-----------+------------+--------------------------+
|   seq_num |       time | qem1_current2_mean_value |
+-----------+------------+--------------------------+
Cannot find EGLConfig, returning null config
Unable to find an X11 visual which matches EGL config 0
/usr/local/bin/bsui: line 69: 32298 Segmentation fault      $ipython_cmd "$@"
```
The error is unrelated, since it appears even for a simple MPL plotting:
```
In [2]: import matplotlib.pyplot as plt

In [3]: plt.imshow(np.random.random([100, 100]))
Cannot find EGLConfig, returning null config
Unable to find an X11 visual which matches EGL config 0
/usr/local/bin/bsui: line 69: 32519 Segmentation fault      $ipython_cmd "$@"
```

**Comment by mrakitin** [comment]
@tacaswell any ideas about the error ^^^?

**Pull request merged**
